### ISSUE TITLE
Filter for Sync-ADUsertoAzureADAdministrativeUnitMember

### ISSUE THREAD

**Issue by DaveyRance** [MS-LUF/Use-AzureAD#1]
Is it possible to be add a filter for Sync-ADUsertoAzureADAdministrativeUnitMember

We have some users where their UPN is such that they are not getting synced. As a result it will never find them (domain.local upn). 

It would be very good if we could include a filter for UPN's that we wish to get synced by the Sync-ADUsertoAzureADAdministrativeUnitMember command.

**Comment by DaveyRance** [comment]
In the param block if the following was added

        [parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
            [string]$ADUserFilter = '*'

and then the query updated from
$users = Get-ADUser -SearchBase $OU.DistinguishedName -SearchScope Subtree -Filter * -Properties $CloudUPNAttribute

to:
$users = Get-ADUser -SearchBase $OU.DistinguishedName -SearchScope Subtree -Filter $ADUserFilter -Properties $CloudUPNAttribute

Then users would be able to apply custom user filters like users in this OU that have these attributes based on AD filters.

**Comment by MS-LUF** [comment]
nice update, it will be included in the next release.
